<a href="https://colab.research.google.com/github/gabijee/pytorch_tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSORS**


*   a torch.Tensor is a multi-dimential matrix containing elements of a single data type
*   Similar to numpyarray, but works better on GPU than CPU
*   default data type of float32
*   more suitable for deep learning than numpy array



In [ ]:
import torch
import numpy as np

**LIST**

In [ ]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

**Numpy**

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.95045405, 0.39167239, 0.45408136, 0.29723636],
       [0.65713561, 0.24083835, 0.01163236, 0.13015049],
       [0.96114594, 0.39609224, 0.23199203, 0.00910812]])

In [ ]:
np1.dtype

dtype('float64')

**Tensors**

In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
## create a tensor from numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9505, 0.3917, 0.4541, 0.2972],
        [0.6571, 0.2408, 0.0116, 0.1302],
        [0.9611, 0.3961, 0.2320, 0.0091]], dtype=torch.float64)